Fix a bug when not using JSLint
Hello,

I created a webpack project with vue-cli and noticed that I had an error when running `npm run dev` :

```
Error: Cannot find module 'eslint-friendly-formatter'
```

I added the correct code so that module don't get called when you chose to not use any JSLint tool.

Regards,

Romain.